/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mem */

#ifndef _Included_Mem
#define _Included_Mem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mem
 * Method:    alloc
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_Mem_alloc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Mem
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_Mem_free
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
